#define POS_DATA_BLOCK_COUNT        0
#define POS_OCCUPIED_BLOCK_COUNT    1
#define POS_FREE_BLOCK_COUNT        2
#define POS_FILE_SYSTEM_ENTRY_COUNT 3
#define POS_DIRECTORY_COUNT         4
#define POS_FILE_COUNT              5
#define POS_DEVICE_COUNT            6
#define POS_FILES_SIZE              7
#define POS_FILES_OCCUPIED_SIZE     8

#define FSSTAT_DATA_BLOCK_COUNT        (1 << POS_DATA_BLOCK_COUNT)
#define FSSTAT_OCCUPIED_BLOCK_COUNT    (1 << POS_OCCUPIED_BLOCK_COUNT)
#define FSSTAT_FREE_BLOCK_COUNT        (1 << POS_FREE_BLOCK_COUNT)
#define FSSTAT_FILE_SYSTEM_ENTRY_COUNT (1 << POS_FILE_SYSTEM_ENTRY_COUNT)
#define FSSTAT_DIRECTORY_COUNT         (1 << POS_DIRECTORY_COUNT)
#define FSSTAT_FILE_COUNT              (1 << POS_FILE_COUNT)
#define FSSTAT_DEVICE_COUNT            (1 << POS_DEVICE_COUNT)
#define FSSTAT_FILES_SIZE              (1 << POS_FILES_SIZE)
#define FSSTAT_FILES_OCCUPIED_SIZE     (1 << POS_FILES_OCCUPIED_SIZE)
